# Generated by Django 3.0.6 on 2021-02-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_create_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('name', models.CharField(max_length=160)),
                ('Upskills_candidates_on', models.CharField(max_length=500)),
                ('work_experience', models.TextField()),
                ('with_experig', models.TextField()),
            ],
        ),
    ]
