# Generated by Django 3.0.6 on 2021-02-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Demographics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Working_Professionals', models.IntegerField()),
                ('Third_year_students', models.IntegerField()),
                ('Final_year_students', models.IntegerField()),
                ('Experienced_freelancer', models.IntegerField()),
            ],
        ),
    ]
