# Generated by Django 3.0.6 on 2021-02-12 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_student_demographics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Demographic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Working_Professionals', models.IntegerField()),
                ('Third_year_students', models.IntegerField()),
                ('Final_year_students', models.IntegerField()),
                ('Experienced_freelancer', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student_Demographic', to='testapp.Mentor')),
            ],
        ),
        migrations.DeleteModel(
            name='Student_Demographics',
        ),
    ]
